# Packages Loading

In [23]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np 
from joblib import dump


# Chargement les données 

In [10]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [16]:
# Features and target 
x = iris.data
y = iris.target
print(x[0])
print(y[0:5])

[5.1 3.5 1.4 0.2]
[0 0 0 0 0]


# Train and Test Split

In [17]:
seed = 13 
x_train, x_test , y_train , y_test = train_test_split(x, y,
                                                      test_size=0.2, 
                                                      random_state=seed)

## Show the result
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


# Logistic Regression Modele

In [19]:
# max_iter designe le nombre d'itération maximale, cela permet à l'algorithme de converger vers 
## une solution optimale 
logreg = LogisticRegression(multi_class= "auto", max_iter=500)
## Entrainer le modèle 
logreg.fit(x_train, y_train)

LogisticRegression(max_iter=500)

# The train score

In [20]:
logreg.score(x_train, y_train)

0.975

# Predictions

In [22]:
y_pred = logreg.predict(x_test)
print(y_pred)

[1 1 0 2 2 0 2 2 0 1 2 1 1 0 2 0 2 2 1 0 1 0 0 2 1 2 0 2 1 2]


# Score of the test dataset

In [27]:
accuracy = round(accuracy_score(y_test, y_pred),3)
print(accuracy)

0.967


# Save the modele

In [28]:
dump(logreg, "logreg.joblib")

['logreg.joblib']